### PR TITLE
Add support for fog, and tidy up shader.

### PR DESCRIPTION
**Pull request by mattconsto**
Supports Linear, Exponential, and Exponential Squared Fog.

### CODE REVIEW

**Comment by pavelkouril** [comment]
Hi! Thanks for your contribution, however, before I'm willing to merge this, there are some things I want to ask. :)

How come the fog did not work for you? The fog works for me with the latest master by default, in all 3 modes. See the "Tests\Forward-Fog\02-After" test case, and try switching the modes, and all three should work (for Linear, try decreasing the "End" to like 5).

Also, thanks a lot for pointing out the duplicate shader files! I changed the naming structure to be more consistent with my other packages, and probably left this one over.

**Comment by mattconsto** [comment]
I ran Tests\Forward-Fog\02-After with both pavelkouril/unity-lowpoly-shader and mattconsto/unity-lowpoly-shader and at first I was confused as the fog seemed to work fine. However using the latest master in an actual project reveals the difference

For comparison here is the code I propose merging:



And here is the latest master:



Both screenshots are taken with the same settings: Exp2 with a density of 0.018.

It's worth noting that this is only a problem at some angles of light, here's my code:



And the latest master:



It doesn't look wrong or bad, but you can see a lot of detail just missing.

I think this might be an issue with terrains only, or at least it only has a noticeable affect on large objects. The reason the trees and other details pop is that they must use the Terrain/Bark or Leaf shader otherwise billboarding breaks. If I was only using this lowpoly shader they would be hidden in fog.

**Comment by pavelkouril** [comment]
Hmm, interesting, could you take screenshot with standard shader used, to see what fog calculation looks more similiar to the standard shader? I want it to act like the standard shader whenever possible, so I'm for the solution that will look closer to the original. 

I tried to look at the differences, and one of the differences I've found is that you are using a view space for calculation, and my old code used clip position (as do the [official examples](https://docs.unity3d.com/Manual/SL-VertexFragmentShaderExamples.html)).

Also, I see you added a `uniform float unity_FogDensity` - but it's not used anywhere, is it? Also, you removed the fog from the ForwardAdd pass?

**Comment by mattconsto** [comment]
Here's the Standard shader:





Interestingly, the dark scene is darker with the standard shader.

As for the last points, they can all be attributed to me not fully understanding how to write shaders. Changing viewspace to clipposition, removing unity_fogdensity, and removing the fog off declaration has no impact on final image quality. I'm going to update the pull request with these changes.

**Comment by pavelkouril** [comment]
Yours really closer to the original  even though I don't understand why, since I was using it the way it is used in the Unity's standard shaders, after checking Unity shaders source codes.

Also, your looks much more better I guess, so I'll merge it, I just have three small favors to ask:

Revert the rename to `Pavel Kouril/LowPoly`; keep it as `PavelKouril/LowPoly Shader/LowPoly`, to have the naming consistent with my other stuff. :)

Revert the delete of "It works for terrain, but the results are sometimes looking subpar. This is due to the way the Unity terrain works. A separate set of shaders for terrain would be probably needed." from README; this line is still true, the shader is still using the fallback of sampling the terrain textures into one texture, and proper terrain shader using splatmaps will probably be needed one day anyways. 

Revert the formatting changes ({ on the same line as function/loop/etc.) - again, for consistency. :)

**Comment by mattconsto** [comment]
Done, done, and done.

**Comment by pavelkouril** [comment]
Thanks a lot! Squashed and merged!

**Pull request merged**
